# Generated by Django 5.1.2 on 2025-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_exercise_target_muscle_en_exercise_target_muscle_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcategory',
            name='workout_image',
            field=models.ImageField(blank=True, null=True, upload_to='workout-category/'),
        ),
    ]
