# Generated by Django 5.1.2 on 2025-02-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_workoutcategory_workout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('month', 'Monthly'), ('quarter', '3-Month'), ('year', 'Yearly')], default='month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
